language: python
python:
  - "3.4"
  - "3.5"
install:
  - "pip install numpy scipy pandas -f http://nikosonnensche.in/wheels/index.html --trusted-host nikosonnensche.in --no-index"
  - "pip install ."
script: python setup.py test
