language: python
cache:
  - pip: true
python:
  - "3.4"
  - "3.5"
before_install:
  - | 
    mkdir -p $HOME/.config/matplotlib && \
    echo 'backend: agg' > $HOME/.config/matplotlib/matplotlibrc
install:
  - "pip install ."
script: python setup.py test
